"""initial schema

Revision ID: b3a83d900893
Revises: 
Create Date: 2026-05-25 15:07:48.281424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a83d900893'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hex_root', sa.String(length=64), server_default='0000000000000000000000000000000000000000000000000000000000000000', nullable=False),
    sa.Column('session_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('leaf_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_workflow_id', 'sessions', ['workflow_id'], unique=False)
    op.create_table('tree_nodes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('left_hash', sa.String(length=64), nullable=True),
    sa.Column('right_hash', sa.String(length=64), nullable=True),
    sa.Column('parent_hash', sa.String(length=64), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tree_nodes_session_id', 'tree_nodes', ['session_id'], unique=False)
    op.create_index('ix_tree_nodes_workflow_id', 'tree_nodes', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tree_nodes_workflow_id', table_name='tree_nodes')
    op.drop_index('ix_tree_nodes_session_id', table_name='tree_nodes')
    op.drop_table('tree_nodes')
    op.drop_index('ix_sessions_workflow_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('workflows')
    # ### end Alembic commands ###
